import { Entity, PrimaryGeneratedColumn, Column, ManyToOne, JoinColumn, CreateDateColumn, UpdateDateColumn } from 'typeorm';
import { User } from '../../users/entities/user.entity';
import { Contract } from '../../contract/entities/contract.entity';

export enum InvoiceStatus {
  UNCONFIRMED = 'Unconfirmed',
  ISSUED = 'Issued',
  IN_ARREARS = 'In arrears',
  NOTIFICATION1 = 'Notification1',
  NOTIFICATION2 = 'Notification2',
  SUSPENDED = 'Suspended',
  PAID = 'Paid'
}

@Entity('invoices')
export class Invoice {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ unique: true, nullable: true })
  code: string;

  @Column({ type: 'decimal', precision: 10, scale: 2 })
  value: number;

  @Column({ type: 'date' })
  issueDate: Date;

  @Column({ type: 'date' })
  expirationDate: Date;

  @Column({ type: 'date', nullable: true })
  paymentDate: Date;

  @Column({
    type: 'enum',
    enum: InvoiceStatus,
    default: InvoiceStatus.UNCONFIRMED
  })
  status: InvoiceStatus;

  @ManyToOne(() => User, { eager: true })
  @JoinColumn({ name: 'userId' })
  user: User;

  @Column()
  userId: string;

  @ManyToOne(() => Contract, { nullable: true })
  @JoinColumn({ name: 'contractId' })
  contract?: Contract;

  @Column({ nullable: true })
  contractId?: string;

  @Column({ type: 'date', nullable: true })
  periodStart?: Date;

  @Column({ type: 'date', nullable: true })
  periodEnd?: Date;

  @Column({ default: false })
  isAutoGenerated: boolean;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}