import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, In } from 'typeorm';
import { Cron, CronExpression } from '@nestjs/schedule';
import { Invoice, InvoiceStatus } from './entities/invoice.entity';
import { Contract } from '../contract/entities/contract.entity';
import { ContractStatus } from '../contract/enums/contract-status.enum';
import { PaymentMode } from '../contract/enums/payment-mode.enum';
import { GlobalParametersPeriods } from '../global-parameters-periods/entities/global-parameters-periods.entity';

@Injectable()
export class InvoiceGeneratorService {
  private readonly logger = new Logger(InvoiceGeneratorService.name);

  constructor(
    @InjectRepository(Invoice)
    private invoiceRepository: Repository<Invoice>,
    @InjectRepository(Contract)
    private contractRepository: Repository<Contract>,
    @InjectRepository(GlobalParametersPeriods)
    private globalParametersPeriodsRepository: Repository<GlobalParametersPeriods>,
  ) {}

  @Cron(CronExpression.EVERY_DAY_AT_MIDNIGHT)
  async generateInvoices(): Promise<void> {
    this.logger.log('Starting invoice generation process...');
    
    const activeContracts = await this.contractRepository.find({
      where: { status: ContractStatus.ACTIVE },
      relations: ['user', 'package']
    });

    for (const contract of activeContracts) {
      await this.processContract(contract);
    }

    this.logger.log('Invoice generation process completed');
  }

  private async processContract(contract: Contract): Promise<void> {
    const today = new Date();
    const shouldGenerate = await this.shouldGenerateInvoice(contract, today);

    if (shouldGenerate) {
      await this.createInvoiceForContract(contract, today);
    }
  }

  private async shouldGenerateInvoice(contract: Contract, currentDate: Date): Promise<boolean> {
    const { periodStart, periodEnd } = this.calculatePeriod(contract, currentDate);
    
    // Verificar si ya existe una factura para este período
    const existingInvoice = await this.invoiceRepository.findOne({
      where: {
        contractId: contract.id,
        periodStart,
        periodEnd
      }
    });

    return !existingInvoice && this.isGenerationDay(contract, currentDate);
  }

  private isGenerationDay(contract: Contract, currentDate: Date): boolean {
    switch (contract.mode) {
      case PaymentMode.MONTHLY:
        return contract.payday ? currentDate.getDate() === contract.payday : currentDate.getDate() === 1;
      
      case PaymentMode.SEMIANNUAL:
        const startMonth = contract.startDate.getMonth();
        const currentMonth = currentDate.getMonth();
        return (currentMonth - startMonth) % 6 === 0 && currentDate.getDate() === contract.startDate.getDate();
      
      case PaymentMode.ANNUAL:
        return currentDate.getMonth() === contract.startDate.getMonth() && 
               currentDate.getDate() === contract.startDate.getDate();
      
      default:
        return false;
    }
  }

  private calculatePeriod(contract: Contract, currentDate: Date): { periodStart: Date; periodEnd: Date } {
    const periodStart = new Date(currentDate);
    const periodEnd = new Date(currentDate);

    switch (contract.mode) {
      case PaymentMode.MONTHLY:
        periodStart.setDate(1);
        periodEnd.setMonth(periodEnd.getMonth() + 1, 0);
        break;
      
      case PaymentMode.SEMIANNUAL:
        const startMonth = Math.floor(currentDate.getMonth() / 6) * 6;
        periodStart.setMonth(startMonth, 1);
        periodEnd.setMonth(startMonth + 6, 0);
        break;
      
      case PaymentMode.ANNUAL:
        periodStart.setMonth(0, 1);
        periodEnd.setMonth(12, 0);
        break;
    }

    return { periodStart, periodEnd };
  }

  private async createInvoiceForContract(contract: Contract, currentDate: Date): Promise<Invoice> {
    const { periodStart, periodEnd } = this.calculatePeriod(contract, currentDate);
    const issueDate = this.calculateIssueDate(contract, currentDate);
    const expirationDate = new Date(issueDate);
    expirationDate.setDate(expirationDate.getDate() + 30); // 30 días para pagar

    const calculatedValue = await this.calculateInvoiceValue(contract, periodStart, periodEnd);

    const invoice = this.invoiceRepository.create({
      value: calculatedValue,
      issueDate,
      expirationDate,
      status: InvoiceStatus.UNCONFIRMED,
      userId: contract.user.id,
      contractId: contract.id,
      periodStart,
      periodEnd,
      isAutoGenerated: true
    });

    const savedInvoice = await this.invoiceRepository.save(invoice);
    
    this.logger.log(`Generated invoice ${savedInvoice.id} for contract ${contract.id} with value ${calculatedValue}`);
    
    return savedInvoice;
  }

  private async calculateInvoiceValue(contract: Contract, periodStart: Date, periodEnd: Date): Promise<number> {
    let baseValue = Number(contract.value);

    // Si es mensual, dividir entre 12
    if (contract.mode === PaymentMode.MONTHLY) {
      baseValue = baseValue / 12;
    }

    // Obtener parámetros globales activos para el período
    const globalParams = await this.getActiveGlobalParameters(periodStart, periodEnd);
    
    let iva = 0;
    let profitMargin = 0;
    let financingInterest = 0;

    for (const param of globalParams) {
      const value = parseFloat(param.value) / 100; // Convertir porcentaje a decimal
      
      switch (param.globalParameter.code) {
        case 'iva':
          iva = value;
          break;
        case 'profit_margin':
          profitMargin = value;
          break;
        case 'financing_interest':
          financingInterest = value;
          break;
      }
    }

    // Aplicar cálculos
    let finalValue = baseValue;
    finalValue += baseValue * profitMargin; // Agregar margen de ganancia
    finalValue += baseValue * financingInterest; // Agregar interés de financiamiento
    finalValue += finalValue * iva; // Agregar IVA sobre el subtotal

    return Math.round(finalValue * 100) / 100; // Redondear a 2 decimales
  }

  private async getActiveGlobalParameters(periodStart: Date, periodEnd: Date): Promise<GlobalParametersPeriods[]> {
    return await this.globalParametersPeriodsRepository.find({
      where: {
        status: 'active',
        globalParameter: {
          code: In(['iva', 'profit_margin', 'financing_interest'])
        }
      },
      relations: ['globalParameter', 'period']
    });
  }

  private calculateIssueDate(contract: Contract, currentDate: Date): Date {
    const issueDate = new Date(currentDate);
    
    if (contract.mode === PaymentMode.MONTHLY && contract.payday) {
      issueDate.setDate(contract.payday);
    }
    
    return issueDate;
  }

  async generateInvoiceForContract(contractId: string): Promise<Invoice> {
    const contract = await this.contractRepository.findOne({
      where: { id: contractId },
      relations: ['user', 'package']
    });

    if (!contract) {
      throw new Error(`Contract ${contractId} not found`);
    }

    if (contract.status !== ContractStatus.ACTIVE) {
      throw new Error(`Contract ${contractId} is not active`);
    }

    // Verificar si ya existe factura para el período actual
    const currentDate = new Date();
    const { periodStart, periodEnd } = this.calculatePeriod(contract, currentDate);
    
    const existingInvoice = await this.invoiceRepository.findOne({
      where: {
        contractId: contract.id,
        periodStart,
        periodEnd
      }
    });

    if (existingInvoice) {
      throw new Error(`Invoice already exists for current period`);
    }

    return await this.createInvoiceForContract(contract, currentDate);
  }
}